export const AllProducts = [
  {
    id: 121,
    title: "iPhone 5s",
    description:
      "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
    category: "smartphones",
    price: 199.99,
    discountPercentage: 11.85,
    rating: 3.92,
    stock: 65,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "AZ1L68SM",
    weight: 4,
    dimensions: {
      width: 8.49,
      height: 25.34,
      depth: 18.12,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Wyatt Perry",
        reviewerEmail: "wyatt.perry@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Olivia Anderson",
        reviewerEmail: "olivia.anderson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Mateo Nguyen",
        reviewerEmail: "mateo.nguyen@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2903942810911",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/thumbnail.png",
  },
  {
    id: 122,
    title: "iPhone 6",
    description:
      "The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 4.54,
    rating: 3.76,
    stock: 99,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "ZPXH3X9J",
    weight: 8,
    dimensions: {
      width: 16.21,
      height: 22.94,
      depth: 5.63,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Gavin Stanley",
        reviewerEmail: "gavin.stanley@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 3,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2517230562429",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/thumbnail.png",
  },
  {
    id: 123,
    title: "iPhone 13 Pro",
    description:
      "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
    category: "smartphones",
    price: 1099.99,
    discountPercentage: 18.3,
    rating: 3.42,
    stock: 26,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "YGQKHPGK",
    weight: 8,
    dimensions: {
      width: 22.39,
      height: 9.77,
      depth: 19.6,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ryan Graham",
        reviewerEmail: "ryan.graham@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Mason Wright",
        reviewerEmail: "mason.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2986724589988",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png",
  },
  {
    id: 124,
    title: "iPhone X",
    description:
      "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
    category: "smartphones",
    price: 899.99,
    discountPercentage: 14.19,
    rating: 4.96,
    stock: 99,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "9QN3UDUD",
    weight: 10,
    dimensions: {
      width: 27.86,
      height: 8.53,
      depth: 17.07,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "4331405454760",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/thumbnail.png",
  },
  {
    id: 125,
    title: "Oppo A57",
    description:
      "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.",
    category: "smartphones",
    price: 249.99,
    discountPercentage: 12.17,
    rating: 3.1,
    stock: 76,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "J1NO9ULG",
    weight: 3,
    dimensions: {
      width: 29.52,
      height: 11.25,
      depth: 14.41,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Not worth the price!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Owen Fisher",
        reviewerEmail: "owen.fisher@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nora Mills",
        reviewerEmail: "nora.mills@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "1743445108634",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/thumbnail.png",
  },
  {
    id: 126,
    title: "Oppo F19 Pro Plus",
    description:
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.",
    category: "smartphones",
    price: 399.99,
    discountPercentage: 15.62,
    rating: 2.57,
    stock: 92,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "H2TTGWXB",
    weight: 2,
    dimensions: {
      width: 20.35,
      height: 16.4,
      depth: 13.31,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Lillian Bishop",
        reviewerEmail: "lillian.bishop@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Harper Garcia",
        reviewerEmail: "harper.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7451360954140",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/thumbnail.png",
  },
  {
    id: 127,
    title: "Oppo K1",
    description:
      "The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 14.58,
    rating: 3.39,
    stock: 61,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "ELZ94HM3",
    weight: 2,
    dimensions: {
      width: 21.83,
      height: 27.83,
      depth: 27.47,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nathan Reed",
        reviewerEmail: "nathan.reed@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Madison Stewart",
        reviewerEmail: "madison.stewart@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7535531820285",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/3.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/4.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/thumbnail.png",
  },
  {
    id: 128,
    title: "Realme C35",
    description:
      "The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience.",
    category: "smartphones",
    price: 149.99,
    discountPercentage: 16.47,
    rating: 2.56,
    stock: 81,
    tags: ["smartphones", "realme"],
    brand: "Realme",
    sku: "25KENV7J",
    weight: 6,
    dimensions: {
      width: 21.74,
      height: 28.75,
      depth: 22.22,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ava Harrison",
        reviewerEmail: "ava.harrison@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "3119744926904",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/thumbnail.png",
  },
  {
    id: 129,
    title: "Realme X",
    description:
      "The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 2.39,
    rating: 4.42,
    stock: 87,
    tags: ["smartphones", "realme"],
    brand: "Realme",
    sku: "5E11C5C4",
    weight: 1,
    dimensions: {
      width: 29.32,
      height: 16.3,
      depth: 24.12,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Emily Johnson",
        reviewerEmail: "emily.johnson@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "0139612574728",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/thumbnail.png",
  },
  {
    id: 130,
    title: "Realme XT",
    description:
      "The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.",
    category: "smartphones",
    price: 349.99,
    discountPercentage: 3.03,
    rating: 4.14,
    stock: 53,
    tags: ["smartphones", "realme"],
    brand: "Realme",
    sku: "GHDMRAP2",
    weight: 4,
    dimensions: {
      width: 28.82,
      height: 23.44,
      depth: 6.21,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Claire Foster",
        reviewerEmail: "claire.foster@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "3985844484131",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/thumbnail.png",
  },
  {
    id: 131,
    title: "Samsung Galaxy S7",
    description:
      "The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 8.83,
    rating: 4.9,
    stock: 55,
    tags: ["smartphones", "samsung galaxy"],
    brand: "Samsung",
    sku: "VZF4Z58Z",
    weight: 8,
    dimensions: {
      width: 23.33,
      height: 27.33,
      depth: 27.02,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Jace Smith",
        reviewerEmail: "jace.smith@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "8841359359362",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/thumbnail.png",
  },
  {
    id: 132,
    title: "Samsung Galaxy S8",
    description:
      "The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology.",
    category: "smartphones",
    price: 499.99,
    discountPercentage: 2.69,
    rating: 3.69,
    stock: 75,
    tags: ["smartphones", "samsung galaxy"],
    brand: "Samsung",
    sku: "GLXQQKBF",
    weight: 6,
    dimensions: {
      width: 6.88,
      height: 8.96,
      depth: 18.13,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Christopher West",
        reviewerEmail: "christopher.west@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Hazel Evans",
        reviewerEmail: "hazel.evans@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "1337599403784",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/thumbnail.png",
  },
  {
    id: 133,
    title: "Samsung Galaxy S10",
    description:
      "The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.",
    category: "smartphones",
    price: 699.99,
    discountPercentage: 0.97,
    rating: 2.81,
    stock: 40,
    tags: ["smartphones", "samsung galaxy"],
    brand: "Samsung",
    sku: "5GJFL98I",
    weight: 3,
    dimensions: {
      width: 28.23,
      height: 7.35,
      depth: 10.68,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Elijah Hill",
        reviewerEmail: "elijah.hill@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "0311929399881",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/thumbnail.png",
  },
  {
    id: 134,
    title: "Vivo S1",
    description:
      "The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.",
    category: "smartphones",
    price: 249.99,
    discountPercentage: 4.25,
    rating: 2.83,
    stock: 13,
    tags: ["smartphones", "vivo"],
    brand: "Vivo",
    sku: "BG6974E7",
    weight: 1,
    dimensions: {
      width: 28.83,
      height: 26.69,
      depth: 23.12,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Alice Smith",
        reviewerEmail: "alice.smith@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Harper Kelly",
        reviewerEmail: "harper.kelly@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Lillian Simmons",
        reviewerEmail: "lillian.simmons@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 3,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "4070349673041",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/thumbnail.png",
  },
  {
    id: 135,
    title: "Vivo V9",
    description:
      "The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 14.57,
    rating: 3.1,
    stock: 19,
    tags: ["smartphones", "vivo"],
    brand: "Vivo",
    sku: "N9WFE2WH",
    weight: 5,
    dimensions: {
      width: 27.29,
      height: 9.73,
      depth: 14.79,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Elijah Stewart",
        reviewerEmail: "elijah.stewart@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "1506104702332",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/thumbnail.png",
  },
  {
    id: 136,
    title: "Vivo X21",
    description:
      "The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.",
    category: "smartphones",
    price: 499.99,
    discountPercentage: 7.32,
    rating: 2.75,
    stock: 0,
    tags: ["smartphones", "vivo"],
    brand: "Vivo",
    sku: "KSF00BOC",
    weight: 7,
    dimensions: {
      width: 5.72,
      height: 16.47,
      depth: 27.76,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "Out of Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Bella Grant",
        reviewerEmail: "bella.grant@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 4,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2543504494043",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/thumbnail.png",
  },
  {
    id: 78,
    title: "Apple MacBook Pro 14 Inch Space Grey",
    description:
      "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
    category: "laptops",
    price: 1999.99,
    discountPercentage: 9.25,
    rating: 3.13,
    stock: 39,
    tags: ["laptops", "apple"],
    brand: "Apple",
    sku: "QDKO6NRJ",
    weight: 4,
    dimensions: {
      width: 12.38,
      height: 21.55,
      depth: 27.95,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Hunter Gordon",
        reviewerEmail: "hunter.gordon@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Emma Wilson",
        reviewerEmail: "emma.wilson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "David Martinez",
        reviewerEmail: "david.martinez@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.622Z",
      updatedAt: "2024-05-23T08:56:21.622Z",
      barcode: "3883623063065",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png",
  },
  {
    id: 79,
    title: "Asus Zenbook Pro Dual Screen Laptop",
    description:
      "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.",
    category: "laptops",
    price: 1799.99,
    discountPercentage: 9.21,
    rating: 3.14,
    stock: 38,
    tags: ["laptops"],
    brand: "Asus",
    sku: "4A9KFMBG",
    weight: 8,
    dimensions: {
      width: 19.67,
      height: 11.05,
      depth: 14.32,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Ava Harris",
        reviewerEmail: "ava.harris@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Brayden Fleming",
        reviewerEmail: "brayden.fleming@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.622Z",
      updatedAt: "2024-05-23T08:56:21.622Z",
      barcode: "2899455033799",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/thumbnail.png",
  },
  {
    id: 80,
    title: "Huawei Matebook X Pro",
    description:
      "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.",
    category: "laptops",
    price: 1399.99,
    discountPercentage: 15.25,
    rating: 4.62,
    stock: 34,
    tags: ["laptops"],
    brand: "Huawei",
    sku: "U2CBNNB0",
    weight: 9,
    dimensions: {
      width: 22.11,
      height: 11.11,
      depth: 23.07,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Samantha Howard",
        reviewerEmail: "samantha.howard@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Brayden Fleming",
        reviewerEmail: "brayden.fleming@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.622Z",
      updatedAt: "2024-05-23T08:56:21.622Z",
      barcode: "1232723732298",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/thumbnail.png",
  },
  {
    id: 81,
    title: "Lenovo Yoga 920",
    description:
      "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.",
    category: "laptops",
    price: 1099.99,
    discountPercentage: 7.77,
    rating: 2.98,
    stock: 71,
    tags: ["laptops"],
    brand: "Lenovo",
    sku: "MST9WZQY",
    weight: 7,
    dimensions: {
      width: 11.02,
      height: 14.45,
      depth: 24.09,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.623Z",
      updatedAt: "2024-05-23T08:56:21.623Z",
      barcode: "9590995785298",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/thumbnail.png",
  },
  {
    id: 82,
    title: "New DELL XPS 13 9300 Laptop",
    description:
      "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.",
    category: "laptops",
    price: 1499.99,
    discountPercentage: 11.7,
    rating: 2.98,
    stock: 18,
    tags: ["laptops"],
    brand: "Dell",
    sku: "XBJJ446X",
    weight: 10,
    dimensions: {
      width: 12.09,
      height: 6.43,
      depth: 15.69,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Daniel Taylor",
        reviewerEmail: "daniel.taylor@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.623Z",
      updatedAt: "2024-05-23T08:56:21.623Z",
      barcode: "0358629687929",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/thumbnail.png",
  },
  {
    id: 93,
    title: "Brown Leather Belt Watch",
    description:
      "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    category: "mens-watches",
    price: 89.99,
    discountPercentage: 15.01,
    rating: 4.47,
    stock: 69,
    tags: ["watches", "leather watches"],
    brand: "Fashion Timepieces",
    sku: "WGZ21MSA",
    weight: 10,
    dimensions: {
      width: 18.39,
      height: 10.82,
      depth: 10.52,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Eli Ward",
        reviewerEmail: "eli.ward@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Stella Hughes",
        reviewerEmail: "stella.hughes@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "9559180055872",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/thumbnail.png",
  },
  {
    id: 94,
    title: "Longines Master Collection",
    description:
      "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.",
    category: "mens-watches",
    price: 1499.99,
    discountPercentage: 0.64,
    rating: 2.64,
    stock: 65,
    tags: ["watches", "luxury watches"],
    brand: "Longines",
    sku: "LA7B9XEV",
    weight: 2,
    dimensions: {
      width: 5.83,
      height: 12.48,
      depth: 7.65,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Victoria McDonald",
        reviewerEmail: "victoria.mcdonald@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Mia Rodriguez",
        reviewerEmail: "mia.rodriguez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "1865008250672",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png",
  },
  {
    id: 95,
    title: "Rolex Cellini Date Black Dial",
    description:
      "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.",
    category: "mens-watches",
    price: 8999.99,
    discountPercentage: 14.28,
    rating: 3.61,
    stock: 84,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "J3GPKQW0",
    weight: 6,
    dimensions: {
      width: 12.17,
      height: 27.99,
      depth: 10.36,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Gavin Stanley",
        reviewerEmail: "gavin.stanley@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Stella Hughes",
        reviewerEmail: "stella.hughes@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "8917585155737",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/thumbnail.png",
  },
  {
    id: 96,
    title: "Rolex Cellini Moonphase",
    description:
      "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.",
    category: "mens-watches",
    price: 12999.99,
    discountPercentage: 5.7,
    rating: 4.52,
    stock: 33,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "LUZDIKKR",
    weight: 5,
    dimensions: {
      width: 28.07,
      height: 13.43,
      depth: 10.81,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jacob Cooper",
        reviewerEmail: "jacob.cooper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Elijah Cruz",
        reviewerEmail: "elijah.cruz@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "0330714338454",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png",
  },
  {
    id: 97,
    title: "Rolex Datejust",
    description:
      "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.",
    category: "mens-watches",
    price: 10999.99,
    discountPercentage: 9.69,
    rating: 4.94,
    stock: 11,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "86V20NWJ",
    weight: 5,
    dimensions: {
      width: 9.68,
      height: 7.29,
      depth: 5.67,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Max Russell",
        reviewerEmail: "max.russell@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jonathan Pierce",
        reviewerEmail: "jonathan.pierce@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Asher Scott",
        reviewerEmail: "asher.scott@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "4957618378388",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/thumbnail.png",
  },
  {
    id: 98,
    title: "Rolex Submariner Watch",
    description:
      "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.",
    category: "mens-watches",
    price: 13999.99,
    discountPercentage: 0.82,
    rating: 2.97,
    stock: 35,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "XFGRO0O5",
    weight: 5,
    dimensions: {
      width: 5.22,
      height: 27.59,
      depth: 16.93,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Emily Brown",
        reviewerEmail: "emily.brown@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Julian James",
        reviewerEmail: "julian.james@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "6567997358364",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/thumbnail.png",
  },
  {
    id: 190,
    title: "IWC Ingenieur Automatic Steel",
    description:
      "The IWC Ingenieur Automatic Steel watch is a durable and sophisticated timepiece. With a stainless steel case and automatic movement, it combines precision and style for watch enthusiasts.",
    category: "womens-watches",
    price: 4999.99,
    discountPercentage: 5.76,
    rating: 2.58,
    stock: 85,
    tags: ["watches", "luxury watches"],
    brand: "IWC",
    sku: "OJF7AK1J",
    weight: 4,
    dimensions: {
      width: 12.27,
      height: 5.91,
      depth: 8.71,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "3417342002384",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/thumbnail.png",
  },
  {
    id: 191,
    title: "Rolex Cellini Moonphase",
    description:
      "The Rolex Cellini Moonphase watch is a masterpiece of horology. Featuring a moon phase complication, it showcases the craftsmanship and elegance that Rolex is renowned for.",
    category: "womens-watches",
    price: 15999.99,
    discountPercentage: 18.76,
    rating: 3.41,
    stock: 66,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "E8CYFYQL",
    weight: 5,
    dimensions: {
      width: 22.54,
      height: 20.15,
      depth: 25.37,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Leah Henderson",
        reviewerEmail: "leah.henderson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Mateo Nguyen",
        reviewerEmail: "mateo.nguyen@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "3517608890772",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png",
  },
  {
    id: 192,
    title: "Rolex Datejust Women",
    description:
      "The Rolex Datejust Women's watch is an iconic timepiece designed for women. With a timeless design and a date complication, it offers both elegance and functionality.",
    category: "womens-watches",
    price: 10999.99,
    discountPercentage: 17.72,
    rating: 3.53,
    stock: 31,
    tags: ["watches", "luxury watches", "women's watches"],
    brand: "Rolex",
    sku: "VKQ2UNB9",
    weight: 8,
    dimensions: {
      width: 14.53,
      height: 29.73,
      depth: 10.22,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Evan Reed",
        reviewerEmail: "evan.reed@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Isabella Jackson",
        reviewerEmail: "isabella.jackson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "6032534220602",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/thumbnail.png",
  },
  {
    id: 193,
    title: "Watch Gold for Women",
    description:
      "The Gold Women's Watch is a stunning accessory that combines luxury and style. Featuring a gold-plated case and a chic design, it adds a touch of glamour to any outfit.",
    category: "womens-watches",
    price: 799.99,
    discountPercentage: 6.37,
    rating: 3.03,
    stock: 94,
    tags: ["watches", "women's watches"],
    brand: "Fashion Gold",
    sku: "N6I9YEWM",
    weight: 8,
    dimensions: {
      width: 5.9,
      height: 13.64,
      depth: 23.65,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Lucas Allen",
        reviewerEmail: "lucas.allen@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Bella Gonzalez",
        reviewerEmail: "bella.gonzalez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Michael Johnson",
        reviewerEmail: "michael.johnson@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "0793324106392",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/thumbnail.png",
  },
  {
    id: 194,
    title: "Women's Wrist Watch",
    description:
      "The Women's Wrist Watch is a versatile and fashionable timepiece for everyday wear. With a comfortable strap and a simple yet elegant design, it complements various styles.",
    category: "womens-watches",
    price: 129.99,
    discountPercentage: 17.34,
    rating: 2.93,
    stock: 55,
    tags: ["watches", "women's watches"],
    brand: "Fashion Co.",
    sku: "36T6X4M3",
    weight: 8,
    dimensions: {
      width: 24.74,
      height: 25.89,
      depth: 8.18,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Emily Brown",
        reviewerEmail: "emily.brown@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Mila Hernandez",
        reviewerEmail: "mila.hernandez@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "7588684177028",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/thumbnail.png",
  },
];
